#%RAML 1.0 Trait
usage: Defines common Rest API headers

headers:
  Content-Type:
    description: This is the format for what the API sends
    type: string
    default: application/json
  Accept:
    description: This is the format for what the API receives
    type: string
    default: application/json
